# Generated by Django 3.1.3 on 2020-11-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=190, null=True, verbose_name='Name')),
                ('roll', models.CharField(blank=True, max_length=190, null=True, verbose_name='Roll')),
                ('gender', models.CharField(blank=True, max_length=190, null=True, verbose_name='Gender')),
                ('physics', models.IntegerField(blank=True, null=True, verbose_name='Physics')),
                ('chemistry', models.IntegerField(blank=True, null=True, verbose_name='Chemistry')),
                ('maths', models.IntegerField(blank=True, null=True, verbose_name='Maths')),
            ],
            options={
                'verbose_name': 'Exam data',
                'verbose_name_plural': 'Exam Data',
            },
        ),
    ]
